razuahammed707/ileap

- app/auth/signin/page.tsx
- app/layout.tsx
- lib/auth/index.ts
- lib/models/schema.ts
- package.json
- pnpm-lock.yaml
--google signup enabled
--nextauth configured
> next auth configured for google signup and sign in

- app/(authLayout)/organizer-signup/components/OrganizerStep3Form.tsx
- app/(authLayout)/organizer-signup/page.tsx
- app/(authLayout)/organizer-signup/types.ts
added organization orboarding  view according to figma
> added organization view according to figma

- app/(authLayout)/volunteer-signup/components/Step3Form.tsx
- app/(authLayout)/volunteer-signup/page.tsx
- components/forms/DateTimeRangePicker.tsx
- package.json
- pnpm-lock.yaml
volunteer sign up page is now mobile responsive
> volunteer sign up page is now mobile responsive

- app/(withLayout)/volunteer/page.tsx
- components/layout/volunteer/homepage/HomePageCategories.tsx
The home page and card view is done according to the feedback
> the home page and card view is done according to the feedback

- components/layout/volunteer/homepage/MiniGallery.tsx
mobile responsive volunteer homepage
> mobile responsive volunteer homepage

- app/(auth)/signup/page.tsx
- app/(landing)/about/page.tsx
- app/(landing)/faq/page.tsx
- app/(landing)/layout.tsx
- app/(landing)/page.tsx
- app/(withLayout)/volunteer/page.tsx
- components/Footer.tsx
- components/RegistrationBanner.tsx
- components/TopNavigationBar.tsx
- components/forms/FormInput.tsx
- components/layout/landing/about/AboutHero.tsx
- components/layout/landing/ausleap/about/WhatIsAusLEAP.tsx
- components/layout/landing/ausleap/about/WorkshopOverview.tsx
- components/layout/landing/faq/FAQHero.tsx
- components/layout/landing/landing-page/Hero.tsx
- components/layout/landing/landing-page/VideoTestimonial.tsx
- components/layout/landing/landing-page/Volunteer.tsx
- components/layout/volunteer/VolunteerProfileForm.tsx
--Cleaned the landing pages added validation to sign up
--Removed static contents
--Added user name and email to top navigation bar
> Added user name and email to top navigation bar

- components/TopNavigationBar.tsx
deleted unnecessary folder and links from top navigation bar
> Cleaned up

- components/TopNavigationBar.tsx
> fixed image loading issue

- app/(withLayout)/volunteer/opportunities/[id]/page.tsx
- app/(withLayout)/volunteer/page.tsx
- components/UpdatedFooter.tsx
The UpdatedFooter component has been added to the volunteer homepage and opportunity detail page to provide consistent footer content across these pages. This change ensures that users have access to contact information and social media links in a unified footer design.
> feat: add UpdatedFooter component to volunteer pages

- components/UpdatedFooter.tsx
- components/layout/volunteer/homepage/HomePageCategories.tsx
…tunities UI
- Replace Lucide icons with React Icons in UpdatedFooter for consistency
- Add date and time details to volunteer opportunities in HomePageCategories
- Introduce ConfirmationModal for applying to opportunities
- Remove redundant 'View all' link and improve card layout
> refactor(components): update icon imports and enhance opportunity confirmation

- components/layout/volunteer/homepage/HomePageCategories.tsx
- components/modals/ConfirmationModal.tsx
Refine the styling of ConfirmationModal by updating the rounded corners and adjust the layout, spacing, and dimensions of components in HomePageCategories for better visual consistency and readability.
> style: adjust UI styling for ConfirmationModal and HomePageCategories

- components/layout/volunteer/homepage/HomePageCategories.tsx
Restructured the volunteer opportunity data in HomePageCategories.tsx by removing redundant entries, shortening descriptions, and reordering items for better clarity and maintainability. Simplified the code for improved readability.
> refactor(volunteer/homepage): reorganize and simplify volunteer opportunity data

- components/layout/volunteer/homepage/HomePageCategories.tsx
Updated the descriptions of volunteer events to provide more detailed information about the roles and their impact. Also corrected the date for the "Easy Care Gardening" event to ensure accuracy.
> docs(volunteer/homepage): update event descriptions and date for clarity

- components/layout/auth/OrganizationSignup.tsx
- components/layout/auth/VolunteerSignup.tsx
- server/db/interfaces/organization-profile.ts
- server/db/interfaces/user.ts
- server/db/interfaces/volunteer-profile.ts
- server/db/models/organization-profile.ts
- server/db/models/user.ts
- server/db/models/volunteer-profile.ts
- server/modules/opportunity/index.ts
- server/modules/users/index.ts
- server/modules/users/users.validation.ts
- server/modules/volunteers/index.ts
--Modified user, volunteer_profile, and organization_profile model
--Refactored volunteer and organization signup
> Refactor data model , refactor volunteer and organization signup

- app/(withLayout)/organization/opportunity/create/_components/BasicInformation.tsx
- app/(withLayout)/organization/opportunity/create/page.tsx
- components/layout/auth/OrganizationSignup.tsx
- components/layout/auth/VolunteerSignup.tsx
- hooks/useAuthCheck.ts
- server/db/interfaces/opportunity.ts
- server/db/interfaces/user.ts
- server/db/models/opportunity.ts
- server/db/models/user.ts
- server/modules/opportunity/index.ts
- server/modules/opportunity/opportunities.validation.ts
- server/modules/users/index.ts
- server/modules/users/users.validation.ts
--Refactored, user, opportunity, volunteer_profile, organization_profile model 
--Refactored related integattion, hooks
> Get all opportunies endpoint added; not yet integrated

- components/layout/volunteer/homepage/HomePageCategories.tsx
Introduce a new tab to filter favorite opportunities and enable toggling favorites.
> feat(volunteer): add favorites tab and toggle functionality

- app/(withLayout)/volunteer/organizer/[_id]/page.tsx
- components/buttons/FavoriteButton.tsx
- components/layout/organization/home/OrganizationHomepage.tsx
- components/layout/volunteer/homepage/HomePageCategories.tsx
- components/modals/ConfirmationModal.tsx
- hooks/useFavorite.ts
- hooks/useVolunteerApplication.ts
- server/db/interfaces/favorite-opportunity.ts
- server/db/models/favorite-opportunity.ts
- server/index.ts
- server/modules/volunteer-application/index.ts
- server/modules/volunteer-application/volunteer-application.validation.ts
- server/modules/volunteer-profile/favorite-opportunity/favorite-opportunity.validation.ts
- server/modules/volunteer-profile/favorite-opportunity/index.ts
- server/modules/volunteer-profile/index.ts
- Updated API calls in `OrganizerDetailPage` and `OrganizationHomepage` to use the new `applications` endpoint.
- Introduced `FavoriteButton` component for managing favorite opportunities.
- Refactored `HomePageCategories` to utilize the new favorite functionality and removed local state management for favorites.
- Added new hooks and server routes for handling favorite opportunities, including toggling favorites and fetching favorite status.
- Created necessary validation schemas and database models for favorite opportunities.
> refactor(volunteer): updated API calls and introduced favorite functionality

- app/(withLayout)/organization/opportunity/list/components/OpportunityTabs.tsx
- app/(withLayout)/organization/opportunity/list/page.tsx
- components/layout/ProtectedLayout.tsx
- components/layout/organization/home/OrganizationHomepage.tsx
- package.json
- pnpm-lock.yaml
- server/modules/opportunity/index.ts
- types/opportunities.ts
- Added @tanstack/react-table for enhanced table functionality in the OpportunitiesPage.
- Implemented pagination and dynamic data fetching for opportunities using TRPC.
- Updated OpportunityTabs component for better layout and styling.
- Refactored ProtectedLayout to improve structure and responsiveness.
- Adjusted Opportunity type to include organization_profile for better data handling.
> feat(opportunity): integrated @tanstack/react-table for opportunity listing

- app/(withLayout)/organization/opportunities/[id]/page.tsx
- app/(withLayout)/organization/opportunities/page.tsx
- components/TopNavigationBar.tsx
- components/UserMenu.tsx
- components/layout/organization/opportunities/OpportunityTabs.tsx
- server/modules/opportunity/index.ts
- server/modules/organisation-recruitment/index.ts
- server/services/mail/constants.ts
- server/services/mail/templates/recruitment_confirmation.handlebars
- types/navigation.ts
- types/opportunities.ts
- utils/constants/navigation.ts
- utils/helpers/sendApplicationConfirmationMail.ts
- utils/helpers/sendRecruitmentConfirmationMail.ts
- Updated OpportunitiesPage to display applicant and recruit counts dynamically.
- Modified OpportunityDetailsPage to show the number of applicants and recruits.
- Enhanced OpportunityTabs component to reflect the count of open opportunities.
- Implemented backend logic to fetch applicant and recruit counts for each opportunity.
- Added recruitment confirmation email functionality upon successful recruitment.
> feat(opportunity): enhance opportunity details and applicant management

- app/(withLayout)/organization/opportunities/[id]/page.tsx
- components/layout/messages/MessageUI.tsx
- Introduced a modal for creating groups within the OpportunityDetailsPage, allowing users to group recruited volunteers.
- Updated the messaging logic to invalidate group data upon sending messages, ensuring real-time updates.
- Enhanced the MessageUI component to sort conversations and groups by the last message time, improving user experience.
> added a modal for confirming group creation

- components/form-input/FormSelect.tsx
- components/form-input/SelectField.tsx
- components/layout/auth/OrgDetailsStep.tsx
- components/layout/auth/OrganizationSignup.tsx
- components/layout/organisation/OrganizationProfile.tsx
- server/db/models/organization-profile.ts
- server/modules/users/index.ts
- server/modules/users/users.validation.ts
- Add comprehensive validation for organization type, opportunity types, and required skills
- Improve form state management with better type safety and debugging
- Implement proper error handling and logging throughout the profile update flow
- Update backend schema and model to enforce validation rules
- Add debug logging to track form state and submission process
> feat(organization): added  Organization Profile section to update profile of the organizations

- components/navbar/MobileMenu.tsx
- components/navbar/SearchBar.tsx
- components/navbar/TopBar.tsx
- components/navbar/TopNavigationBar.tsx
- components/navbar/search/DesktopSearch.tsx
- components/navbar/search/MobileSearch.tsx
- components/navbar/search/SearchInput.tsx
- components/navbar/search/SearchSuggestions.tsx
- components/navbar/search/index.ts
- package.json
- pnpm-lock.yaml
- Included framer-motion version 12.14.0 in package.json and updated pnpm-lock.yaml.
- Removed unused "Post an opportunity" link from MobileMenu for cleaner UI.
- Refactored TopBar and TopNavigationBar for improved readability and structure.
> feat(dependencies): add framer-motion for enhanced animations

- components/layout/organisation/find-volunteer/index.tsx
- components/navbar/SearchBar.tsx
- Enhanced code formatting for better readability, including consistent line breaks and indentation.
- Updated the search input and modal handling for improved user experience.
- Added an onClick handler to the overlay in the SearchBar component to close it when clicked.
> refactor(find-volunteer): improve code readability and formatting

- components/layout/auth/OrganizationSignup.tsx
- components/layout/organisation/dashboard/ActiveContent.tsx
- components/layout/organisation/dashboard/DraftContent.tsx
- components/layout/organisation/dashboard/OpenContent.tsx
- components/layout/organisation/dashboard/OrganisationDashboard.tsx
- server/db/models/index.ts
- server/modules/opportunity/applicants.ts
refactor(OrganizationSignup): simplify useEffect dependency for form state management
- Updated the type definitions for active contracts and draft/open opportunities in the dashboard components to use 'any[]' instead of specific types.
- Removed the 'ActiveContract' interface to streamline the code.
- Adjusted the OrganisationDashboard component to accommodate these changes for improved maintainability.
>  simplify contract and opportunity type definitions

- components/layout/organisation/dashboard/InviteMentorDialog.tsx
- components/layout/organisation/dashboard/OrganisationDashboard.tsx
- components/ui/alert-dialog.tsx
- pnpm-lock.yaml
- server/db/interfaces/user.ts
- server/db/models/organization-mentor.ts
- server/index.ts
- server/modules/organization-mentors/index.ts
- server/services/mail/constants.ts
- server/services/mail/templates/mentor_invitation.handlebars
- utils/helpers/sendMentorInvitationMail.ts
- Introduced InviteMentorDialog component to the OrganisationDashboard for inviting mentors.
- Updated the dashboard to fetch and utilize the organization profile ID for mentor invitations.
- Refactored AlertDialog components for improved structure and consistency.
- Added mentor-related routes and constants in the server for future functionality.
> feat(dashboard): added InviteMentorDialog and integrate organization profile ID

- components/layout/messages/MessageUI.tsx
- components/layout/messages/components/ChatArea.tsx
- components/layout/messages/components/ConversationHeader.tsx
- Updated MessageUI to select the correct conversation based on group status.
- Enhanced ChatArea to handle group and user conversations more effectively, ensuring proper data retrieval.
- Simplified user name display in ConversationHeader by removing fallback to 'Unknown User'.
> refactor(messages): improve conversation handling in MessageUI and ChatArea components

- app/(withLayout)/organization/opportunities/[id]/page.tsx
- components/layout/organisation/home/OrganizationOpportunities.tsx
- Added an image banner to the OpportunityDetailsPage for better visual representation.
- Updated OrganizationOpportunities component to display organization logos and location information.
- Introduced badges for commitment type and opportunity categories for improved clarity and organization.
- Enhanced layout and styling for a more user-friendly experience.
> feat(opportunity): enhance opportunity details and listing with images and location badges

- app/(withLayout)/organization/opportunities/create/page.tsx
- Changed the redirect path after successfully creating an opportunity from the opportunity list to the organization overview page for improved navigation.
> fix(opportunity): update redirect after opportunity creation

- components/layout/auth/OrganizationSignup.tsx
- components/navbar/UserMenu.tsx
- server/modules/users/index.ts
- server/services/mail/templates/mentor_invitation.handlebars
- types/navigation.ts
feat(auth): added admin and mentor roles to user types and cleaned up email templates
Extended UserRole type to include admin and mentor roles update UserMenu to handle new roles for organization profiles
modify user router to support role-based queries simplify organization signup flow by removing unused params.
> feat(auth): added admin and mentor roles to user types and cleaned up email templates

- components/layout/organisation/home/OrganizationHomepage.tsx
- components/navbar/UserMenu.tsx
- Introduced MessageDialog component to facilitate communication with selected volunteers.
- Updated handleConnect function to open the dialog with the selected volunteer's details.
- Enhanced loading state handling and improved user feedback when no volunteers are found in the list.
> feat(organization): add message dialog for volunteer connection

- app/(withLayout)/[role]/profile/page.tsx
- app/(withLayout)/components/VolunteerProfile.tsx
- app/(withLayout)/organization/browse-volunteer/page.tsx
- app/(withLayout)/search/page.tsx
- app/layout.tsx
- components/layout/auth/OrganizationSignup.tsx
- components/layout/messages/components/Sidebar.tsx
- components/layout/organisation/dashboard/OrganisationDashboard.tsx
- components/layout/organisation/home/FilterSidebar.tsx
- components/layout/organisation/home/OrganizationHomepage.tsx
- components/layout/organisation/opportunities/PostContent.tsx
- components/layout/organisation/opportunities/Sidebar.tsx
- components/navbar/SearchBar.tsx
- components/navbar/TopBar.tsx
- contexts/SearchContext.tsx
- server/modules/opportunity/index.ts
- Updated ProfilePage and BrowseVolunteerPage to utilize ProtectedLayout for consistent layout structure.
- Enhanced OrganizationHomepage to leverage search context for filtering volunteers.
- Modified SearchBar to support admin role and improved search handling across components.
> Route fixation

- app/layout.tsx
- components/GlobalSSEProvider.tsx
- components/navbar/TopNavigationBar.tsx
- hooks/useConversations.ts
- hooks/useGlobalSSE.ts
- hooks/useMessageSubscription.ts
- hooks/useMessages.ts
- Wrapped children components in GlobalSSEProvider to enable global Server-Sent Events (SSE) management.
- Updated useMessageSubscription to utilize the new global SSE manager, simplifying the connection logic and enhancing message handling.
- Removed redundant code related to EventSource management, streamlining the subscription process.
> refactor(layout): integrated GlobalSSEProvider for improved message handling

- components/layout/volunteer/find-opportunity/OrganizationsTab.tsx
- server/modules/organization-profile/index.ts
- Implement backend endpoint for fetching organizations with search, filtering and pagination
- Create frontend component with search functionality, category filters and sorting
- Add pagination support for organization listings
- Include opportunity counts for each organization
> feat(organizations): Added organization listing with search, filters and sorting 

- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/find-opportunity/OpportunityList.tsx
- Replaced loading skeletons with Card components for better visual consistency.
- Introduced OpportunityCard component to encapsulate opportunity details and interactions.
- Changed all instances of '/organization' to '/organisation' in routing logic to ensure uniformity across the application.
- Introduced a tab configuration for better organization of volunteer opportunities and organizations.
- Updated the tab structure to dynamically render content based on the selected tab.
- Improved state management for active tab selection.
> refactor(volunteer): updated FindOpportunities component for improved UI and structure

- app/test-sse/page.tsx
- components/layout/volunteer/find-opportunity/FilterBar.tsx
- components/layout/volunteer/find-opportunity/OpportunitiesHeader.tsx
- components/layout/volunteer/find-opportunity/OpportunitiesTab.tsx
- contexts/SearchContext.tsx
- server/modules/opportunity/index.ts
- Implemented a comprehensive filter system in the FilterBar component, allowing users to search by keyword, location, and commitment type.
- Added active filter display to improve user experience.
- Integrated a debug button in the TestSSEPage to fetch and display opportunity statistics.
- Updated the OpportunitiesTab to utilize the new filter context and handle loading and empty states more effectively.
- Enhanced backend query logic to support new filtering capabilities, including availability and commitment type adjustments.
> feat(volunteer): Enhanced opportunity filtering and debugging features opportunities

- app/(withLayout)/organisation/opportunities/page.tsx
- components/layout/organisation/opportunities/OpportunityTabs.tsx
- components/layout/volunteer/find-opportunity/AdBanner.tsx
- components/layout/volunteer/find-opportunity/FilterBar.tsx
- components/layout/volunteer/find-opportunity/OpportunitiesTab.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/find-opportunity/OrganizationsTab.tsx
- components/layout/volunteer/find-opportunity/index.tsx
- components/navbar/MobileMenu.tsx
- Introduced a mobile-friendly card layout for displaying opportunities, improving accessibility on smaller screens.
- Added new OpportunityCard component to encapsulate opportunity details, including organization info, start date, and applicant counts.
- Updated layout styles for better responsiveness and user experience across devices.
- Enhanced the OpportunitiesPage to conditionally render mobile and desktop views based on screen size.
- Improved tab navigation and filter bar for better usability.
> feat(opportunities): enhanced mobile view for opportunities page with mobile card views and new components

- app/(withLayout)/organisation/opportunities/page.tsx
- components/layout/organisation/opportunities/OpportunityTabs.tsx
- components/layout/volunteer/find-opportunity/AdBanner.tsx
- components/layout/volunteer/find-opportunity/FilterBar.tsx
- components/layout/volunteer/find-opportunity/OpportunitiesTab.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/find-opportunity/OrganizationsTab.tsx
- components/layout/volunteer/find-opportunity/index.tsx
- components/navbar/MobileMenu.tsx
Reverts razuahammed707/ileap#153
> Revert "feat(opportunities): enhanced mobile view for opportunities page with mobile card views and new components"

- components/layout/volunteer/find-opportunity/FilterBar.tsx
- components/layout/volunteer/find-opportunity/OpportunitiesHeader.tsx
Reverts razuahammed707/ileap#154
> Revert "Browse opportunities"

- components/layout/organisation/opportunities/Sidebar.tsx
- components/layout/shared/OpportunitySidebar.tsx
- server/config/mongoose.ts
- server/db/interfaces/organization-profile.ts
- server/db/models/index.ts
- server/db/models/organization-profile.ts
- Updated the interface name from IOrgnizationPofile to IOrganizationProfile in Sidebar.tsx, OpportunitySidebar.tsx, organization-profile.ts, and organization-profile model.
- Ensured consistent usage of the corrected interface across the application.
- Added import statement for models in mongoose configuration to ensure proper registration.
> fix: correct spelling of IOrganizationProfile in multiple files

- app/(withLayout)/organisation/opportunities/page.tsx
- app/globals.css
- app/test-sse/page.tsx
- components/layout/organisation/dashboard/OrganisationDashboard.tsx
- components/layout/organisation/opportunities/OpportunityTabs.tsx
- components/navbar/MobileMenu.tsx
- components/navbar/NavLink.tsx
- server/db/models/opportunity.ts
- server/modules/opportunity/index.ts
- utils/helpers/getGreeting.ts
- Introduced a mobile card component for displaying opportunities, improving accessibility on smaller screens.
- Updated the OpportunitiesPage layout for better responsiveness, including adjustments to padding and flex properties.
- Added a scrollbar hide utility in globals.css for a cleaner mobile experience.
- Enhanced the OpportunityTabs component with a mobile slider layout and a separator for improved navigation.
- Integrated new icons for better visual representation in the MobileMenu.
- Added a test opportunities endpoint in the backend for debugging purposes.
> feat(opportunities): enhanced mobile and desktop views for opportunities

- app/(withLayout)/organisation/opportunities/page.tsx
- components/buttons/CreateOpportunityButton.tsx
- components/layout/organisation/dashboard/OrganisationDashboard.tsx
- components/layout/organisation/opportunities/PostContent.tsx
- components/layout/organisation/opportunities/Sidebar.tsx
- components/layout/shared/OpportunitySidebar.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/home-page/HomePageCategories.tsx
- components/layout/volunteer/home-page/OrganizationOpportunities.tsx
- components/layout/volunteer/home-page/PostContent.tsx
- components/layout/volunteer/home-page/Sidebar.tsx
- components/modals/ConfirmationModal.tsx
- server/db/interfaces/opportunity.ts
- server/db/models/opportunity.ts
- server/modules/opportunity/index.ts
- types/opportunities.ts
- Updated opportunity data structure to use nested objects for date and time, enhancing clarity and consistency.
- Replaced direct references to start_date and start_time with the new date and time objects across various components.
- Introduced CreateOpportunityButton for streamlined opportunity posting in the UI.
- Improved opportunity display logic in multiple components to accommodate the new structure.
> feat(opportunities): refactor opportunity date and time structure

- components/layout/volunteer/find-opportunity/FilterBar.tsx
- components/layout/volunteer/home-page/OrganizationOpportunities.tsx
- Updated padding and margin for improved spacing in the FilterBar component.
- Added mobile-specific layout for search and filter options, ensuring a better user experience on smaller screens.
- Enhanced text sizes for better readability across mobile and desktop views.
- Introduced clear filters button and improved styling for commitment type checkboxes and location input.
> feat(filter-bar): enhance mobile responsiveness and layout adjustments

- app/(withLayout)/components/VolunteerProfile.tsx
- components/layout/organisation/VolunteerCard.tsx
- components/layout/organisation/find-volunteer/VolunteerModal.tsx
- components/layout/organisation/opportunities/VolunteerModal.tsx
- components/navbar/TopNavigationBar.tsx
- components/ui/random-avatar.tsx
- hooks/useConversations.ts
- hooks/useMessages.ts
refactor(volunteer): replace static images with random avatars
style(volunteer): improve responsive layout in profile component
perf(messages): increase polling frequency for real-time updates
> feat(avatars): implement random avatar component and update usage

- components/layout/auth/OrgSignupStep.tsx
- components/layout/auth/SignupStep.tsx
- components/layout/organisation/find-volunteer/index.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/navbar/TopBar.tsx
- Reformatted code for better readability and consistency.
- Added a hero section with a title and description to enhance user engagement.
- Adjusted the display of active filters and pagination for improved clarity.
- Updated dialog and filter sidebar integration for better user experience.
> refactor(volunteer): improved layout and enhanced UI elements in BrowseVolunteer component

- app/(withLayout)/organisation/opportunities/[id]/page.tsx
- app/(withLayout)/search/page.tsx
- app/(withLayout)/volunteer/dashboard/opportunity/[id]/page.tsx
- app/(withLayout)/volunteer/dashboard/page.tsx
- components/layout/messages/components/ChatArea.tsx
- components/layout/messages/components/ConversationHeader.tsx
- components/layout/messages/components/ConversationHeaderOptimized.tsx
- components/layout/messages/components/GroupMemberManagement.tsx
- components/layout/organisation/dashboard/index.tsx
- components/layout/organisation/opportunities/ApplicantsCard.tsx
- components/layout/volunteer/find-opportunity/index.tsx
- components/navbar/MobileMenu.tsx
- components/navbar/TopBar.tsx
- server/db/interfaces/opportunity-mentor.ts
- server/db/models/index.ts
- server/db/models/opportunity-mentor.ts
- server/modules/message/index.ts
- server/modules/opportunity/index.ts
- server/modules/organisation-recruitment/index.ts
- server/modules/organization-mentors/index.ts
- Added functionality to fetch opportunity mentors and assign them as group admins during group creation.
- Updated OpportunityDetailsPage to include mentor IDs in group creation logic.
- Enhanced ApplicantsCard to allow marking volunteers as mentors for specific opportunities.
- Introduced UI elements for filtering and managing applicants based on mentor status.
- Improved ConversationHeader to display mentor and admin counts distinctly.
> feat(opportunities): implement mentor management features and enhance applicant interactions

- components/layout/volunteer/find-opportunity/FilterSidebar.tsx
- server/db/models/mentor-invitation.ts
- utils/constants/opportunities.ts
-refactor(mentor-invitation): remove unused token index from MentorInvitationSchema
-refactor(opportunities): update opportunity categories and remove active filters display
-Updated opportunity categories to be more specific 
-Removed redundant active filters display from FilterSidebar component to simplify the UI.
> -refactor(opportunities): updated opportunity categories and remove active filters display

- components/layout/volunteer/VolunteerProfileForm.tsx
- Add toggle between view and edit modes with proper state management
- Implement loading state while fetching profile data
- Improve UI with cards, icons, and better organization
- Add cancel button to exit edit mode without saving
> feat(volunteer-profile): enhance profile form with view/edit modes and UI improvements

- components/buttons/BackButton.tsx
- components/layout/organisation/OrganizationProfile.tsx
- Replace custom button with shadcn/ui Button component in BackButton
- Improve layout and styling with new Card components
- Remove debug console logs and unused effects
- Add loading state and better error handling
> refactor(organization-profile): improve UI and add toggle between edit and view modes for organization profile

- components/navbar/TopBar.tsx
- Added usePathname hook to determine if the current path is 'signin'.
- Updated the role-based message display in the TopBar to conditionally render based on the signin path.
- Improved styling logic for the signup link and button based on the current path.
> feat(navbar): enhanced TopBar component with conditional rendering and styling

- components/layout/shared/OpportunityDetailContainer.tsx
- server/modules/message/index.ts
- server/modules/organization-mentors/index.ts
- Modified routing logic in OpportunityDetailContainer to dynamically direct users based on their role.
- Enhanced group creation permissions for volunteers, allowing them to create groups only if assigned as mentors for opportunities.
- Improved organization access checks for marking and removing mentors, ensuring only authorized users can perform these actions.
> refactor(opportunity-detail): update message routing and enhance group creation permissions

- components/layout/organisation/OrganizationProfile.tsx
- components/navbar/UserMenu.tsx
- Updated all instances of "Organization" to "Organisation" in OrganizationProfile and UserMenu components for consistency across the application.
> refactor(organization): standardize terminology to "Organisation"

- app/(withLayout)/volunteer/organisation/[_id]/page.tsx
- components/layout/auth/OrgProfileStep.tsx
- components/layout/messages/MessageUI.tsx
- components/layout/messages/components.tsx
- components/layout/messages/components/Avatar.tsx
- components/layout/messages/components/ChatArea.tsx
- components/layout/messages/components/ConversationHeader.tsx
- components/layout/messages/components/ConversationHeaderOptimized.tsx
- components/layout/messages/components/ConversationList.tsx
- components/layout/messages/components/CreateGroupDialog.tsx
- components/layout/messages/components/GroupMemberManagement.tsx
- components/layout/messages/components/MessageBubble.tsx
- components/layout/messages/components/Sidebar.tsx
- components/layout/messages/components/UserList.tsx
- components/layout/organisation/OrganizationProfile.tsx
- components/layout/shared/PostSidebar.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/home-page/OrganizationOpportunities.tsx
- components/layout/volunteer/home-page/Sidebar.tsx
- components/modals/ConfirmationModal.tsx
- components/navbar/UserMenu.tsx
- hooks/useMessages.ts
- server/db/interfaces/group.ts
- server/db/models/group.ts
- server/modules/message/index.ts
- types/message.ts
- utils/constants/suburb.ts
- Replaced avatar prop with image in Avatar component for consistency.
- Simplified Avatar rendering logic to use RandomAvatar when no image is provided.
- Enhanced ConversationHeader and MessageBubble components to utilize the new image prop.
- Updated various components to reflect changes in user data structure, ensuring proper image display.
- Improved group management features by adding opportunityId to group schema and related logic.
> refactor(messages): update avatar handling and optimize conversation header

- components/form-input/ProfilePictureUpload.tsx
- components/layout/organisation/OrganizationProfile.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
…
- Added a uniqueId prop to the ProfilePictureUpload component to allow multiple instances on the same page without ID conflicts.
- Updated the OrganizationProfile component to utilize the uniqueId for both admin and organization profile picture uploads.
- Improved user feedback on profile picture updates with distinct success messages based on the type of update.
> feat(profile): enhance ProfilePictureUpload component with uniqueId prop for multiple instances

- components/buttons/ApplyButton.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- components/layout/volunteer/home-page/HomePageCategories.tsx
- components/layout/volunteer/home-page/OrganizationOpportunities.tsx
- components/layout/volunteer/home-page/PostContent.tsx
- server/modules/volunteer-application/index.ts
- server/services/notification.ts
- server/services/opportunity-archiver.ts
…
- Enhanced ApplyButton component to accept an opportunityDate prop and determine if the opportunity has ended.
- Updated related components to pass opportunity date information.
- Implemented server-side validation to prevent applications for ended opportunities.
> feat(apply-button): add opportunity date handling to disable button for ended opportunities

- components/layout/organisation/dashboard/index.tsx
…te from dashboard
- Removed the section displaying the time since the contract started to streamline the dashboard layout and improve clarity.
> refactor(organisation-dashboard): remove display of contract start dashboard

- app/(withLayout)/[role]/settings/page.tsx
- components/layout/organisation/dashboard/UserManagementTable.tsx
- components/layout/organisation/opportunities/ApplicantsCard.tsx
- components/navbar/UserMenu.tsx
- Replaced existing avatar implementations with the new UserAvatar component in OrganizationSettingsPage, UserManagementTable, ApplicantsCard, and UserMenu for improved consistency and code clarity.
- Enhanced user display by including profile images alongside names in relevant components.
> refactor: integrate UserAvatar component across various pages

- app/(withLayout)/organisation/opportunities/create/_components/BasicInformation.tsx
- app/(withLayout)/view-profile/organisation/details/[_id]/page.tsx
- components/layout/organisation/OrganizationProfile.tsx
- components/layout/organisation/opportunities/Sidebar.tsx
- components/layout/shared/PostSidebar.tsx
- components/layout/volunteer/home-page/PostContent.tsx
- utils/validation/opportunity.ts
- Made the email_contact field optional in the OpportunityFormValues type to enhance flexibility.
- Updated the BasicInformation component to reflect the optional nature of the email contact, modifying the label and help text accordingly.
- Removed unused user data from the OrganizerDetailPage to streamline the component.
- Commented out the display of user email and contact information in the Sidebar and PostSidebar components for cleaner presentation.
- Adjusted the opportunity validation schema to allow for optional email contact input.
> refactor(opportunity): update contact information handling and validation

- components/layout/organisation/OrganizationProfileView.tsx
- Updated the layout of the OrganizationProfileView component for improved user experience.
- Added loading and error states with visually distinct backgrounds and icons.
- Introduced new UI components such as Card and Badge for better organization of information.
- Enhanced the display of organization details, including a hero section with a cover image and improved accessibility features.
> refactor(organizationProfile): enhance UI and error handling

- app/(withLayout)/organisation/opportunities/[id]/edit/page.tsx
- app/(withLayout)/organisation/opportunities/create/page.tsx
- components/layout/messages/components/ChatArea.tsx
- components/layout/organisation/OrganizationProfile.tsx
- components/layout/organisation/dashboard/UserManagementTable.tsx
- components/layout/volunteer/find-opportunity/OpportunityCard.tsx
- hooks/useEditOpportunity.ts
- Updated the opportunity creation and editing processes to ensure optional fields are properly formatted before submission.
- Added dependencies to useEffect hooks in EditOpportunityPage and ChatArea for improved state management.
- Replaced img tag with Image component in OrganizationProfile for better performance and optimization.
- Included pending state indicators in UserManagementTable for improved user feedback.
> refactor(opportunity): enhance form data handling and validation

- components/form-input/MultiSelectField.tsx
- components/layout/auth/VolunteerSignup.tsx
- components/ui/multi-select.tsx
- package.json
- pnpm-lock.yaml
- Updated MultiSelectField to handle the value prop more safely by ensuring it is always an array, preventing potential errors when a non-array value is passed.
- Modified the MultiSelect component to initialize and update selected values correctly, ensuring consistent behavior when value or defaultValue is undefined or null.
- Enhanced VolunteerSignup component to initialize interested_on and interested_categories as empty arrays in the default values, improving form handling.
> feat(multi-select): ensure value is always an array in MultiSelectField

- components/layout/auth/DetailedProfileStep.tsx
- components/layout/volunteer/VolunteerProfileForm.tsx
- server/modules/volunteer-profile/index.ts
…
- Modified the DetailedProfileStep and VolunteerProfileForm components to reset form fields to undefined instead of empty strings when switching study status.
- Updated the volunteer profile router to ensure consistent handling of undefined values for related fields, improving data integrity and form behavior.
> refactor(profile): update form field resets to use undefined instead of empty strings
